# Generated by Django 4.2.1 on 2023-05-11 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infoposts', '0002_newsmodel_delete_root'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsmodel',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
