# Generated by Django 4.2.1 on 2023-05-11 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infoposts', '0004_alter_newsmodel_options_newsmodel_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsmodel',
            options={'verbose_name': 'News'},
        ),
    ]
